export interface PakistaniCity {
  name: string;
  province: string;
}

export const PAKISTANI_PROVINCES = [
  'Punjab',
  'Sindh',
  'Khyber Pakhtunkhwa',
  'Balochistan',
  'Islamabad Capital Territory',
  'Azad Jammu & Kashmir',
  'Gilgit-Baltistan',
] as const;

export const PAKISTANI_CITIES: PakistaniCity[] = [
  // Major Federal & Punjab
  { name: 'Islamabad', province: 'Islamabad Capital Territory' },
  { name: 'Lahore', province: 'Punjab' },
  { name: 'Faisalabad', province: 'Punjab' },
  { name: 'Rawalpindi', province: 'Punjab' },
  { name: 'Gujranwala', province: 'Punjab' },
  { name: 'Multan', province: 'Punjab' },
  { name: 'Sialkot', province: 'Punjab' },
  { name: 'Bahawalpur', province: 'Punjab' },
  { name: 'Sargodha', province: 'Punjab' },
  { name: 'Gujrat', province: 'Punjab' },
  { name: 'Sheikhupura', province: 'Punjab' },
  { name: 'Jhang', province: 'Punjab' },
  { name: 'Rahim Yar Khan', province: 'Punjab' },
  { name: 'Kasur', province: 'Punjab' },
  { name: 'Sahiwal', province: 'Punjab' },
  { name: 'Okara', province: 'Punjab' },
  { name: 'Wah Cantt', province: 'Punjab' },
  { name: 'Dera Ghazi Khan', province: 'Punjab' },
  { name: 'Chiniot', province: 'Punjab' },
  { name: 'Kamoke', province: 'Punjab' },
  { name: 'Hafizabad', province: 'Punjab' },
  { name: 'Sadiqabad', province: 'Punjab' },
  { name: 'Burewala', province: 'Punjab' },
  { name: 'Khanewal', province: 'Punjab' },
  { name: 'Muzaffargarh', province: 'Punjab' },
  { name: 'Mandi Bahauddin', province: 'Punjab' },
  { name: 'Jhelum', province: 'Punjab' },
  { name: 'Khanpur', province: 'Punjab' },
  { name: 'Pakpattan', province: 'Punjab' },
  { name: 'Daska', province: 'Punjab' },
  { name: 'Gojra', province: 'Punjab' },
  { name: 'Muridke', province: 'Punjab' },
  { name: 'Bahawalnagar', province: 'Punjab' },
  { name: 'Samundri', province: 'Punjab' },
  { name: 'Jaranwala', province: 'Punjab' },
  { name: 'Chishtian', province: 'Punjab' },
  { name: 'Attock', province: 'Punjab' },
  { name: 'Vehari', province: 'Punjab' },
  { name: 'Kot Abdul Malik', province: 'Punjab' },
  { name: 'Ferozwala', province: 'Punjab' },
  { name: 'Chakwal', province: 'Punjab' },
  { name: 'Kamalia', province: 'Punjab' },
  { name: 'Ahmedpur East', province: 'Punjab' },
  { name: 'Kot Addu', province: 'Punjab' },
  { name: 'Wazirabad', province: 'Punjab' },
  { name: 'Layyah', province: 'Punjab' },
  { name: 'Taxila', province: 'Punjab' },
  { name: 'Khushab', province: 'Punjab' },
  { name: 'Mianwali', province: 'Punjab' },
  { name: 'Lodhran', province: 'Punjab' },
  { name: 'Hasilpur', province: 'Punjab' },
  { name: 'Bhakkar', province: 'Punjab' },

  // Sindh
  { name: 'Karachi', province: 'Sindh' },
  { name: 'Hyderabad', province: 'Sindh' },
  { name: 'Sukkur', province: 'Sindh' },
  { name: 'Larkana', province: 'Sindh' },
  { name: 'Nawabshah (Shaheed Benazirabad)', province: 'Sindh' },
  { name: 'Mirpur Khas', province: 'Sindh' },
  { name: 'Kotri', province: 'Sindh' },
  { name: 'Shikarpur', province: 'Sindh' },
  { name: 'Jacobabad', province: 'Sindh' },
  { name: 'Khairpur', province: 'Sindh' },
  { name: 'Dadu', province: 'Sindh' },
  { name: 'Tando Allahyar', province: 'Sindh' },
  { name: 'Tando Adam', province: 'Sindh' },
  { name: 'Umerkot', province: 'Sindh' },
  { name: 'Shahdadkot', province: 'Sindh' },
  { name: 'Badin', province: 'Sindh' },
  { name: 'Ghotki', province: 'Sindh' },
  { name: 'Kandhkot', province: 'Sindh' },

  // Khyber Pakhtunkhwa
  { name: 'Peshawar', province: 'Khyber Pakhtunkhwa' },
  { name: 'Mardan', province: 'Khyber Pakhtunkhwa' },
  { name: 'Mingora (Swat)', province: 'Khyber Pakhtunkhwa' },
  { name: 'Kohat', province: 'Khyber Pakhtunkhwa' },
  { name: 'Abbottabad', province: 'Khyber Pakhtunkhwa' },
  { name: 'Dera Ismail Khan', province: 'Khyber Pakhtunkhwa' },
  { name: 'Mansehra', province: 'Khyber Pakhtunkhwa' },
  { name: 'Swabi', province: 'Khyber Pakhtunkhwa' },
  { name: 'Nowshera', province: 'Khyber Pakhtunkhwa' },
  { name: 'Kabal', province: 'Khyber Pakhtunkhwa' },
  { name: 'Haripur', province: 'Khyber Pakhtunkhwa' },
  { name: 'Bannu', province: 'Khyber Pakhtunkhwa' },
  { name: 'Charsadda', province: 'Khyber Pakhtunkhwa' },

  // Balochistan
  { name: 'Quetta', province: 'Balochistan' },
  { name: 'Turbat', province: 'Balochistan' },
  { name: 'Khuzdar', province: 'Balochistan' },
  { name: 'Hub', province: 'Balochistan' },
  { name: 'Chaman', province: 'Balochistan' },
  { name: 'Gwadar', province: 'Balochistan' },
  { name: 'Sibi', province: 'Balochistan' },
  { name: 'Zhob', province: 'Balochistan' },

  // Azad Jammu & Kashmir
  { name: 'Muzaffarabad', province: 'Azad Jammu & Kashmir' },
  { name: 'Mirpur', province: 'Azad Jammu & Kashmir' },
  { name: 'Rawalakot', province: 'Azad Jammu & Kashmir' },
  { name: 'Kotli', province: 'Azad Jammu & Kashmir' },
  { name: 'Bhimber', province: 'Azad Jammu & Kashmir' },

  // Gilgit-Baltistan
  { name: 'Gilgit', province: 'Gilgit-Baltistan' },
  { name: 'Skardu', province: 'Gilgit-Baltistan' },
  { name: 'Hunza', province: 'Gilgit-Baltistan' },
];

